name: build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: ./.github/actions/setup-pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Upload built project
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          overwrite: true
          retention-days: 1
          name: build-artifacts-${{ github.run_id }}
