name: build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Upload built project
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          path: ./dist
          overwrite: true
          retention-days: 1
          name: build-artifacts-${{ github.run_id }}
